#message:2F:(FotB_0000)
{
[Style right]
Hmm..[BR]
The forest feels different from[BR]
when I left this morning...[BR]
[Wait][End]
}


#message:2F:(FotB_0001)
{
[Style right]
Let's be careful![BR]
[Wait][End]
}


#message:2F:(FotB_0002)
{
[Style right]
Getting lost in this weather[BR]
is a death sentence![BR]
[Wait][End]
}


#message:2F:(FotB_0003)
{
[Style Inspect]
The gate won't move, it's jammed.[BR]
[Wait][End]
}


#message:2F:(FotB_0004)
{
[Style Inspect]
There are noises coming from[BR]
the rock.[BR]
[Wait][Next]
It sounds like snickering.[BR]
[Wait][End]
}

